### PR TITLE
Fix travis CI

### PR DESCRIPTION
**Pull request by eiriksm**
Hello there. Just noticed you have a travis integration going, but it errors out, and does not run any tests.

This pull request fixes that. I considered adding that flashy "build passing" badge to the README as well, but that would be up to you I guess :)

By the way, I removed testing for node 0.11, since node-usb is known to not work (nonolith/node-usb#39)

Thanks for this tool, I'll check it out once my tessel reaches my mailbox.

### CODE REVIEW

**Comment by NickHeiner** [comment]
Cool, thanks! I saw that CI was failing but I thought that the `before_install` entry would be more complex so I procrastinated on fixing it. 

Is it really necessary to have a `script` entry? Doesn't travis run `npm test` by default? 

I would definitely be up for the "build passing" badge!

**Comment by eiriksm** [comment]
> Is it really necessary to have a script entry? Doesn't travis run npm test by default?

Actually, no. I did not know that though, thanks! Although I usually put some other CI stuff there, like test coverage, so I need the scripts part anyway.

Fixed the `before_install` to be even more simple, and added a badge to README

**Comment by NickHeiner** [comment]
Great! If you squash this into a single commit, we'll be good to go.

**Comment by eiriksm** [comment]
You got it :)

**Pull request merged**
